#ifndef __DIANRU_OBCODE_H__
#define __DIANRU_OBCODE_H__
#define getDianruDeviceOrientation getFowardActivityView
#define setDianruRequestLaseTimeWithUrl setReplaceImage
#define dianruViewload FowardTabBar
#define dianruStartEGOUpdate SleepTableCell
#define dianruSpendScoreResultCallback NextCell
#define getDianruMainBounds getPrintTableViewCell
#define dianruObjectForKey PrintProgress
#define dianruDidJumpedView HashLabel
#define YQL_V CollectSegment
#define getDianruAppId getHoldActivityView
#define dianruFindview QueryWindow
#define YQLHttpActionExecer NewNavigationBar
#define dianruWithMySelf ParseProgress
#define YQLAlignCenter CreateTableCell
#define YQLANIMATION_TYPE CompileButton
#define dianruQueryString RunToolBar
#define dianruResizeToFit FunctionTableViewCell
#define dianruAddRefreshView PutToolBar
#define YQLMacros PrintView
#define dianruEnable CreateProgress
#define dianruRequestBlock RunLabel
#define dianruImageFor StartWithButton
#define dianruTimeout StartWithWindow
#define YQLTextureInfo HoldTableViewCell
#define dianruExpire DoAlertView
#define YQLViewUnknow PutAlertView
#define dianruParseEvent QueryToolBar
#define dianruParseFloat QueryNavigationBar
#define dianruDidReportedView HoldAlertView
#define YQLTextureVertical SetWindow
#define YQLReqestResultType DeleteWebView
#define YQLViewCell HashCell
#define getDianruSpendScore getNewAlertView
#define YQLTextureHorizontal AddLabel
#define dianruShareIstance FunctionWindow
#define dianruActions FindButton
#define dianruBuildWithName ParseLabel
#define setDianruNode setCreateLabel
#define dianruDuration NewSegment
#define YQLNotificationAction PrintNavigationBar
#define dianruExec PrintWebView
#define dianruLoadView IteratorView
#define dianruApplicationKey HashPicker
#define addDianruStyle SleepWebView
#define dianruRequestSpace HashToolBar
#define dianruCreate StartWithView
#define dianruContext ApendToolBar
#define dianruCancel MatchSlider
#define YQLAlignLeft StartWithToolBar
#define YQLViewText GetTableViewCell
#define initWithDianruContext initIndexSlider
#define dianruName DeletePicker
#define dianruParseTextAttr CompileWebView
#define getDianruMacAddress getDoTable
#define setDianruArrowData setHashAlertView
#define YQLHttpRequest DoTableCell
#define dianruSubview DeleteTabBar
#define setDianruDelegateNull setParseButton
#define dianruReadNetDataTaskFor ApendCell
#define dianruStopLoadAnimation CompareLabel
#define dianruFsPath SetWebView
#define dianruEnableUseRadius CompareNavigationBar
#define dianruDidDataReceivedView ReplaceTableViewCell
#define YQLActionNode IndexSegment
#define dianruWakeup HoldTable
#define YQLFontBold QueryPicker
#define YQLViewSection SetCell
#define YQLUrlCache HashTabBar
#define dianruMovieFinishedCallback HashSlider
#define YQLViewSimple GetAlertView
#define dianruLoadData IteratorWindow
#define dianruHide CompareView
#define dianruResult matchTabBar
#define dianruRemove ReadTabBar
#define YQLFontStyle_ALL IndexPicker
#define YQLViewDelegate IteratorButton
#define refreshDianruTableHeaderDidTriggerRefresh WaitActivityView
#define dianruRect QuerySlider
#define dianruStartRotation CompareSegment
#define YQLViewTable FowardTableViewCell
#define addDianruChild CreateNavigationBar
#define dianruPurge ReplaceSegment
#define YQLHttpAction ApendView
#define YQLOPullRefreshLoading CompareTabBar
#define dianruText MatchTable
#define dianruImage CompareWindow
#define _dianruBuild WaitTableViewCell
#define setDianruImageWithContent setDeleteTable
#define dianruExecuteAnimation FowardPicker
#define getDianruLocation getRunAlertView
#define YQLRefreshTableHeaderDelegate BuildView
#define dianruInitialize DeleteWindow
#define setDianruResult setMatchTabBar
#define YQLSectionView StartWithCell
#define dianruStopEGOUpdate BuildImage
#define YQLFontDELETE NextButton
#define refreshDianruScrollViewDidEndDragging DeleteSlider
#define dianruTimes NextImage
#define dianruParent DoSlider
#define dianruHandleSingleFingerEvent ReplaceWindow
#define YQLNode CreateSlider
#define YQLScriptRunner DoSegment
#define YQLAnimationView FowardTableCell
#define YQLViewAnimation NewProgress
#define dianruTarget DoToolBar
#define dianruParseActionNode HashTable
#define dianruUpdateContent StartWithWebView
#define dianruCutStr PutNavigationBar
#define setDianruRefreshArrowImage setBuildTableCell
#define getDianruScore getAddTabBar
#define YQLMediaView CreateWindow
#define refreshDianruTableHeaderDataSourceIsLoading EndWithLabel
#define YQLTexture SetTable
#define YQLViewInterstitial IndexToolBar
#define dianruUrl CollectAlertView
#define dianruLocalIPAddress IndexView
#define refreshDianruScrollViewDataSourceDidFinishedLoading SleepTableViewCell
#define dianruWebViewCallBack FowardToolBar
#define dianruDataFor GetImage
#define YQLDelegate RunImage
#define dianruFsDirectory FowardWebView
#define dianruEncryptWithText SetPicker
#define YQLTableSectionView WaitNavigationBar
#define setDianruState setFindWebView
#define dianruDecodeToUrl RunButton
#define dianruLocation holdPicker
#define YQLTextureType AddSegment
#define dianruDidMainCloseView EndWithTable
#define dianruEvent FowardAlertView
#define YQLViewHtml IndexTable
#define YQLOPullRefreshPulling StartWithTableViewCell
#define dianruExit HoldSegment
#define dianruParseBackground MatchPicker
#define YQLViewRoot FowardNavigationBar
#define YQLAction StartWithTabBar
#define YQLFactory ReadSegment
#define YQLOrientation CollectTable
#define dianruDidViewCloseView CompareTable
#define dianruDeviceOrientationDidChange FowardSlider
#define YQLTextureSimple BuildSegment
#define getDianruImage getSetNavigationBar
#define dianruRun DeleteLabel
#define dianruWrite IteratorTableViewCell
#define YQLInterstitialView NextLabel
#define dianruURLEncodedString HashWebView
#define dianruAppuserid DeleteToolBar
#define dianruExecOne FowardTable
#define YQLViewAction IndexTabBar
#define getDianruMachineName getParseImage
#define dianruKeyForString CompileAlertView
#define dianruShowLoadAnimation IteratorTable
#define dianruWithData NextActivityView
#define dianruMoviePlayerLoadStateChanged CompileNavigationBar
#define dianruFrame matchWindow
#define YQLSimpleView HoldWebView
#define YQLUIModel FunctionLabel
#define dianruDeviceString EndWithWindow
#define dianruCreateWithView ReadSwitch
#define dianruShow BuildSwitch
#define dianruOn FowardCell
#define dianruReportData FunctionButton
#define dianruParseHex FindProgress
#define dianruCacheTimeList SetTableCell
#define YQLScript HoldSlider
#define dianruHTTPResultCallback GetWindow
#define dianruScoreResultCallback RunSwitch
#define dianruSuspend HoldButton
#define getDianruTimestamp getFunctionAlertView
#define dianruDelegate CollectSlider
#define dianruWithUrl CreateImage
#define dianruWithRequst SleepCell
#define getDianruOSVersion getEndWithPicker
#define dianruStartAni CompareActivityView
#define YQLView IteratorPicker
#define YQLFontStyleNode NextWebView
#define dianruStopRotation CompileLabel
#define dianruDisposeContent FindImage
#define dianruFindView QueryButton
#define dianruWithCallback ReplaceTableCell
#define dianruURLDecodedString GetView
#define getDianruUserId getEndWithAlertView
#define YQLTextureLoop CollectLabel
#define YQLViewNode HoldSwitch
#define dianruNode createLabel
#define dianruStopAnimation RunActivityView
#define dianruUrlToDecode QueryTabBar
#define dianruParseInsets GetButton
#define YQLAlign PrintAlertView
#define dianruRegistClickEvent IndexWindow
#define YQLViewLoader GetSegment
#define refreshDianruScrollViewDidScroll ParseTableViewCell
#define YQLTextView ReadLabel
#define YQLEncryptUtil NextToolBar
#define YQLViewUtil WaitProgress
#define YQLRefreshTableView_LastRefresh CreateCell
#define YQLLabelUpdate ReplaceTable
#define dianruView GetSwitch
#define YQLFontNormal FunctionSwitch
#define dianruDecryptWithText SetImage
#define dianruDidViewOpenView EndWithProgress
#define YQLContext PutCell
#define YQLGTMBase64 CompareSwitch
#define dianruParseStyleAttr PutTableCell
#define YQLOPullRefreshNormal EndWithWebView
#define YQLTALKINGTYPE IteratorWebView
#define YQLFontUnderLine PrintWindow
#define YQLSdkInfo NewImage
#define dianruContent createPicker
#define setDianruContent setCreatePicker
#define dianruData FindSwitch
#define dianruForKey QueryLabel
#define onDianruAdClickADID BuildToolBar
#define getDianruScreenFrame getIteratorCell
#define dianruDoneLoadingTableViewData IteratorTableCell
#define dianruClose StartWithTableCell
#define YQLTalkingDataAction IteratorSegment
#define dianruCode FunctionTabBar
#define refreshDianruLastUpdatedDate FunctionCell
#define getDianruHttpFail getWaitButton
#define YQL_TK_CLICK RunTabBar
#define dianruImageResultCallback CompileCell
#define YQLViewType IndexTableCell
#define dianruDecode ReadWebView
#define YQLTableCell CollectPicker
#define YQLCacheRequest ReadButton
#define YQL_TK_DISPLAY NextView
#define YQLStyleNode CompileTableViewCell
#define YQLEngine SleepAlertView
#define dianruReadLocationDataTaskFor IndexButton
#define dianruScreenRotation HoldToolBar
#define dianruEnableRequestWithUrl ParseSwitch
#define YQLTextureFull StartWithImage
#define YQLOpenAction CollectView
#define YQLViewFactory WaitWebView
#define YQLBorder BuildButton
#define YQLFileSystem QueryCell
#define dianruIsModify ApendAlertView
#define dianruCenter PrintTableCell
#define YQLViewImage PutLabel
#define dianruReloadTableViewDataSource HoldProgress
#define YQLDeviceInfo SleepTabBar
#define dianruParseStyle StartWithSegment
#define YQLFontStyle HashSwitch
#define setDianruLocation getHoldPicker
#define dianruParseBorder SleepNavigationBar
#define dianruParseView SetSegment
#define dianruFormat NextAlertView
#define dianruObject StartWithNavigationBar
#define dianruDidClickedView NewView
#define YQLAlignRight CreateActivityView
#define dianruKey WaitImage
#define dianruMasks BuildTabBar
#define YQLRefreshTableHeaderView DoButton
#define dianruPadding GetPicker
#define dianruMethod StartWithAlertView
#define refreshDianruTableHeaderDataSourceLastUpdated DoTableViewCell
#define dianruSpaceUrl ReadActivityView
#define dianruWith CollectWebView
#define dianruDrawType QueryImage
#define dianruLocalWiFiAvailable CompareButton
#define dianruSubviews FunctionToolBar
#define YQLPullRefreshState HashWindow
#define dianruLoadani DeleteActivityView
#define getDianruWithIDFA getReadTableCell
#define dianruParseRect ReplaceToolBar
#define dianruParseColor PrintToolBar
#define dianruTimerAction BuildTableViewCell
#define onDianruAdDisplayADID BuildActivityView
#define dianruTo DoTabBar
#define dianruLoad DoView
#define YQLTalkingData NewTable
#define dianruParseAlign MatchSegment
#define YQLHtmlView AddActivityView
#define dianruDecodeOne DeleteSwitch
#define dianruBuild WaitPicker
#define addDianruEvent DoImage
#define dianruChecksum2 PrintButton
#define dianruAddCallback AddImage
#define dianruChecksum1 PutProgress
#define dianruBind WaitLabel
#define dianruDrawTexture IteratorToolBar
#define setDianruImageWithUrl setPutWebView
#define isDianruJailbroken GetLabel
#define dianruValue MatchProgress
#define getDianruBaseUrl getFowardView
#define dianruCarrierName IndexTableViewCell
#define dianruSubType HoldView
#define YQLTableView SetAlertView
#define dianruParseFontStyle CompileTable
#define YQLViewMedia CollectButton
#define dianruClearup ReplaceSlider
#define dianruAddCell NextSegment
#define dianruState findWebView
#define YQLAlertAction CreateAlertView
#define dianruCloseMain ApendButton
#define dianruType MatchSwitch
#define YQLUtil HoldLabel
#define YQLEventManager AddCell
#define setDianruViewNode setRunTableViewCell
#define setDianruFrame setMatchWindow
#define YQLAnimationAction NextTabBar
#define YQL_TK_UNKNOW DeleteCell
#define dianruCallback ApendSwitch
#define YQLDataCache ReadToolBar
#define YQLLoader ParseNavigationBar
#define dianruStartAniType EndWithCell
#define YQLOpenUDID WaitToolBar
#define YQLLocation DoActivityView
#define YQL_H CompileView
#define dianruUpdate HashTableCell
#define dianruParseViewType FunctionView
#define dianruStartAnimation ReplaceWebView
#define YQLImageView ParseView
#define YQLSDK ReplaceAlertView
#define YQLWebView EndWithView
#define dianruParseTextureType GetCell
#define dianruRequest CollectTableViewCell
#define dianruCheckIsNeedModify FunctionSegment
#define dianruFileIsExists SetButton
#endif /*__DIANRU_OBCODE_H__*/
